apiVersion: v1
kind: Pod
metadata:
  name: signed-pod
spec:
  containers:
    - name: signed-container
      image: ghcr.io/kyverno/test-verify-image:signed   # Assumes this is a signed image

---

apiVersion: v1
kind: Pod
metadata:
  name: unsigned-pod
spec:
  containers:
    - name: unsigned-container
      image: ghcr.io/kyverno/test-verify-image:unsigned   # This is an unsigned image
